import KEY_NAME from './keyName';

const DEFAULT_FORM_DATA = {
  [KEY_NAME.TEMPLATE_ID]: null,
  [KEY_NAME.TEMPLATE_VERSION]: null,
  [KEY_NAME.PROJECT_NAME]: null,
  [KEY_NAME.PROJECT_ON_STREAM]: null,
  [KEY_NAME.PARTICIPATING_INTEREST]: null,
  [KEY_NAME.DRILLING_COST]: null,
  [KEY_NAME.FACILITIES_COST]: null,
  [KEY_NAME.CAPEX]: null,
  [KEY_NAME.EST_FIDAPPROVED]: null,
  [KEY_NAME.PROPOSAL_DATE]: null,
  [KEY_NAME.RKAP]: null,
  [KEY_NAME.REVISION]: false,
  [KEY_NAME.ENTITY_IDS]: [],
  [KEY_NAME.HIER_LVL_2]: null,
  [KEY_NAME.HIER_LVL_3]: null,
  [KEY_NAME.PROJECT_CATEGORY]: null,
  [KEY_NAME.PROJECT_CRITERIA]: null,
  [KEY_NAME.PROJECT_SUB_CRITERIA]: null,
  [KEY_NAME.THRESHOLD]: null,
  [KEY_NAME.PROJECT_WORKFLOW_TYPE]: null,
};

export const DEFAULT_SCOPE_OF_WORK_FORM_DATA = {
  [KEY_NAME.WELL_DRILL_PRODUCER_COUNT]: null,
  [KEY_NAME.WELL_DRILL_INJECTOR_COUNT]: null,
  [KEY_NAME.WELL_WORK_OVER_PRODUCER_COUNT]: null,
  [KEY_NAME.WELL_WORK_OVER_INJECTOR_COUNT]: null,
  [KEY_NAME.PLATFORM]: [],
  [KEY_NAME.PIPELINE]: [],
  [KEY_NAME.COMPRESSOR]: [],
  [KEY_NAME.EQUIPMENT]: [],
};

export const DEFAULT_RESOURCES_FORM_DATA = {
  [KEY_NAME.OIL]: null,
  [KEY_NAME.GAS]: null,
  [KEY_NAME.OIL_EQUIVALENT]: null,
};

export const DEFAULT_ECONOMIC_INDICATOR_FORM_DATA = {
  [KEY_NAME.NET_PRESENT_VALUE]: null,
  [KEY_NAME.PROFITABILITY_INDEX]: null,
  [KEY_NAME.INTERNAL_RATE_OF_RETURN]: null,
  [KEY_NAME.DISCOUNTED_PAY_OUT_TIME]: null,
  [KEY_NAME.PV_IN]: null,
  [KEY_NAME.PV_OUT]: null,
  [KEY_NAME.BENEFIT_COST_RATIO]: null,
};

export default DEFAULT_FORM_DATA;
