const KEY_NAME = {
  TEMPLATE_ID: 'templateId',
  TEMPLATE_VERSION: 'templateVersion',
  PROJECT_ID: 'projectId',
  PROJECT_VERSION: 'projectVersion',
  PROJECT_NAME: 'projectName',
  PROJECT_ON_STREAM: 'projectOnStream',
  PARTICIPATING_INTEREST: 'participatingInterest',
  DRILLING_COST: 'drillingCost',
  FACILITIES_COST: 'facilitiesCost',
  CAPEX: 'capex',
  EST_FIDAPPROVED: 'EstFidapproved',
  PROPOSAL_DATE: 'ProposalDate',
  RKAP: 'Rkap',
  REVISION: 'Revision',
  ENTITY_IDS: 'entityIds',
  HIER_LVL_2: 'hierLvl2',
  HIER_LVL_3: 'hierLvl3',
  HIER_LVL_4: 'hierLvl4',
  PROJECT_CATEGORY: 'projectCategory',
  PROJECT_CRITERIA: 'projectCriteria',
  PROJECT_SUB_CRITERIA: 'projectSubCriteria',
  THRESHOLD: 'threshold',
  PROJECT_WORKFLOW_TYPE: 'projectWorkflowType',
  WELL_DRILL_PRODUCER_COUNT: 'wellDrillProducerCount',
  WELL_DRILL_INJECTOR_COUNT: 'wellDrillInjectorCount',
  WELL_WORK_OVER_PRODUCER_COUNT: 'wellWorkOverProducerCount',
  WELL_WORK_OVER_INJECTOR_COUNT: 'wellWorkOverInjectorCount',
  PLATFORM: 'platform',
  PIPELINE: 'pipeline',
  COMPRESSOR: 'compressor',
  EQUIPMENT: 'equipment',
  OIL: 'Oil',
  GAS: 'Gas',
  OIL_EQUIVALENT: 'OilEquivalent',
  NET_PRESENT_VALUE: 'netPresentValue',
  PROFITABILITY_INDEX: 'profitabilityIndex',
  INTERNAL_RATE_OF_RETURN: 'internalRateOfReturn',
  DISCOUNTED_PAY_OUT_TIME: 'discountedPayOutTime',
  PV_IN: 'pvin',
  PV_OUT: 'pvout',
  BENEFIT_COST_RATIO: 'benefitCostRatio',
  ZONA: 'zona',
  STATUS: 'status',
};

export default KEY_NAME;
