import AdmininstrationMasterData from './AdmininstrationMasterData';
import AdmininstrationWorkflowSettings from './AdmininstrationWorkflowSettings';
import DashboardReport from './DashboardReport';
import DocumentManagement from './documentManagement/DocumentManagement';
import Home from './home/Home';
import MasterPage from './MasterPage';
import DetailProject from './projectManagement/detailProject/DetailProject';
import CreateProject from './projectManagement/createProject/CreateProject';
import AllProjects from './projectManagement/AllProjects';

export { AdmininstrationMasterData };
export { AdmininstrationWorkflowSettings };
export { DashboardReport };
export { DocumentManagement };
export { Home };
export { MasterPage };
export { DetailProject };
export { CreateProject };
export { AllProjects };
